apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracker-productplan.fullname" . }}
  labels:
    {{- include "tracker-productplan.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tracker-productplan.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tracker-productplan.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TRACKER_HOST
              value: {{ .Values.env.tracker.host | quote }}
            - name: TRACKER_SERVICE
              value: {{ .Values.env.tracker.service | quote }}
            - name: PRODUCTPLAN_ROADMAP
              value: {{ .Values.env.productplan.roadmap | quote }}
            - name: PRODUCTPLAN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "tracker-productplan.secretName" . }}
                  key: PRODUCTPLAN_TOKEN
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
