{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracker-productplan.fullname" . }}
  labels:
    {{- include "tracker-productplan.labels" . | nindent 4 }}
type: Opaque
data:
  PRODUCTPLAN_TOKEN: {{ .Values.secret.productplan.token | b64enc | quote }}
{{- end -}}
